# Generated by Django 6.0.1 on 2026-01-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
